# Generated by Django 3.2.3 on 2021-05-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='9d93130d', editable=False, max_length=8, unique=True),
        ),
    ]
