# Generated by Django 3.2.3 on 2021-05-23 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classroom_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwork',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='8fa6d9ac', editable=False, max_length=8, unique=True),
        ),
    ]
