# Generated by Django 3.2.3 on 2021-05-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20210523_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='909c61ba', editable=False, max_length=8, unique=True),
        ),
    ]
