# Generated by Django 3.2.3 on 2021-05-23 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_classroom_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwork',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='9b44e09e', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='classwork',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
